import { getPostBySlug, getPrevNext } from "@/lib/posts";
import Link from "next/link";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { TableOfContents } from "@/components/table-of-contents";
import { CopyableCode } from "@/components/copyable-code";
import ReadingProgress from "@/components/motion/ReadingProgress";
import { SITE_URL } from "@/lib/site";
import { jsonLd } from "@/lib/json-ld";
import { Crosshair } from "@/components/kalka/Interactive";

export const revalidate = 60;

interface Props {
  params: Promise<{ slug: string }>;
}

function readingTime(text: string): number {
  const words = text.trim().split(/\s+/).length;
  return Math.max(1, Math.round(words / 200));
}

// Detect step-by-step articles and extract HowTo steps.
// Matches headings like "Шаг 1:", "Этап 2:", "Шаг первый" (3+ steps = HowTo).
function extractHowToSteps(html: string): { name: string; text: string }[] | null {
  const stepRe = /<h[23][^>]*>((?:Шаг|Этап|Пункт|Step)\s+[\dA-Za-zА-Яа-я]+[:.][^<]*)<\/h[23]>/gi;
  const steps: { name: string; text: string }[] = [];
  let m;
  while ((m = stepRe.exec(html)) !== null) {
    const raw = m[1].replace(/<[^>]+>/g, "").trim();
    // Extract description sentence after the colon, fall back to heading text
    const colonIdx = raw.indexOf(":");
    const name = colonIdx > -1 ? raw.slice(colonIdx + 1).trim() : raw;
    steps.push({ name, text: name });
  }
  return steps.length >= 3 ? steps : null;
}

// Extract FAQ Q&A pairs from HTML generated by the writer.
// Writer outputs: <strong>Question?</strong> followed by <p>Ответ: ...</p>
// Returns empty array if no FAQ section found.
function extractFaq(html: string): { question: string; answer: string }[] {
  const faqSection = html.match(
    /<h2[^>]*>Часто задаваемые вопросы<\/h2>([\s\S]*?)(?=<h2|$)/i
  );
  if (!faqSection) return [];

  const pairs: { question: string; answer: string }[] = [];
  // Match <p><strong>Question?</strong></p><p>Ответ: ...</p>
  const re = /<p>\s*<strong>([^<]+)<\/strong>\s*<\/p>\s*<p>([\s\S]*?)<\/p>/gi;
  let m;
  while ((m = re.exec(faqSection[1])) !== null) {
    const question = m[1].trim();
    // Strip "Ответ: " prefix and any inline HTML tags
    const answer = m[2].replace(/<[^>]+>/g, "").replace(/^Ответ:\s*/i, "").trim();
    if (question && answer) pairs.push({ question, answer });
  }
  return pairs;
}

// The cover image is also the first inline image in content_html. When we show
// the cover as a hero, strip that first occurrence so it isn't repeated.
function stripCoverImage(html: string, src: string | null): string {
  if (!src) return html;
  const esc = src.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const pWrapped = new RegExp(`<p>\\s*<img[^>]*src="${esc}"[^>]*>\\s*</p>`, "i");
  if (pWrapped.test(html)) return html.replace(pWrapped, "");
  return html.replace(new RegExp(`<img[^>]*src="${esc}"[^>]*>`, "i"), "");
}

// Body images come from stored markdown-rendered HTML, so they carry no
// loading hints — every article shipped ~3.5 MB of PNGs eagerly. Rewriting at
// render time fixes all existing posts without a database migration.
// Applied only to in-body images; the cover above stays eager (it is the LCP).
function lazyLoadImages(html: string): string {
  return html.replace(/<img\b([^>]*)>/gi, (tag, attrs: string) => {
    let next = attrs;
    if (!/\bloading=/i.test(next)) next += ' loading="lazy"';
    if (!/\bdecoding=/i.test(next)) next += ' decoding="async"';
    return `<img${next}>`;
  });
}

// The page already renders post.title as the H1. When a generated body repeats
// the title as its own <h1>, the page ships two — demote body H1s to H2 so the
// document keeps exactly one top-level heading.
function demoteBodyH1(html: string): string {
  return html
    .replace(/<h1\b([^>]*)>/gi, "<h2$1>")
    .replace(/<\/h1>/gi, "</h2>");
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const post = await getPostBySlug(slug);

  if (!post) return {};

  const blogUrl = SITE_URL;

  return {
    title: post.title,
    description: post.meta_desc ?? undefined,
    keywords: post.tags ?? undefined,
    openGraph: {
      title: post.title,
      description: post.meta_desc ?? undefined,
      type: "article",
      url: `${blogUrl}/blog/${post.slug}`,
      publishedTime: post.published_at,
      ...(post.cover_image && {
        images: [{ url: post.cover_image, width: 1200, height: 630 }],
      }),
    },
    twitter: {
      card: "summary_large_image",
      title: post.title,
      description: post.meta_desc ?? undefined,
      ...(post.cover_image && { images: [post.cover_image] }),
    },
    alternates: {
      canonical: `${blogUrl}/blog/${post.slug}`,
    },
  };
}

// The end-of-article CTA. Most posts sell the audit, but a post that teases a
// product has to point at that product instead — otherwise the button says
// "write to Telegram" and lands on a sales page.
function resolveCta(ctaUrl: string | null) {
  const href = ctaUrl ?? "https://telegram.me/lyaminvl?text=Аудит";

  if (href.includes("/products/guide")) {
    return {
      href,
      external: false,
      eyebrow: "Гайд",
      title: "Claude как рабочий инструмент",
      text: "128 страниц: контекст, база знаний, каскады моделей и хуки. Два трека — для тех, кто не открывал терминал, и для тех, кому нужен готовый код",
      label: "Забрать гайд →",
    };
  }

  if (href.startsWith("/")) {
    return {
      href,
      external: false,
      eyebrow: "Продукт",
      title: "Посмотреть подробнее",
      text: "Разбор задачи, решение и результат — на отдельной странице",
      label: "Открыть →",
    };
  }

  return {
    href,
    external: true,
    eyebrow: "AI-аудит",
    title: "Автоматизируйте свой бизнес с AI",
    text: "Напишите «Аудит» в Telegram — разберу ваши процессы и предложу конкретное решение",
    label: "Написать в Telegram →",
  };
}

export default async function ArticlePage({ params }: Props) {
  const { slug } = await params;
  const post = await getPostBySlug(slug);

  if (!post) notFound();

  const { prev, next } = await getPrevNext(post);

  const date = new Date(post.published_at).toLocaleDateString("ru-RU", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const minutes = readingTime(post.content_md);
  const blogUrl = SITE_URL;

  const cta = resolveCta(post.cta_url);
  const rawHtml = post.content_html ?? "";
  // With a cover hero, drop the duplicate first inline image from the body.
  const contentHtml = demoteBodyH1(
    lazyLoadImages(
      post.cover_image ? stripCoverImage(rawHtml, post.cover_image) : rawHtml,
    ),
  );
  const faqItems = extractFaq(rawHtml);
  const howToSteps = extractHowToSteps(rawHtml);

  return (
    <div className="k-page">
      <Crosshair />
      <ReadingProgress target=".k-article" />
      <article className="k-article px-[6vw] pb-24 pt-[48px] max-md:px-4">
        {/* Breadcrumbs — pt above is breathing room; the sticky nav reserves its own space in flow. */}
        <nav className="k-mono mx-auto mb-8 max-w-[1200px] px-12 max-md:px-5">
          <Link
            href="/blog"
            className="inline-block bg-white py-2 pr-2 transition-colors hover:text-[#15161a]"
          >
            &larr; Блог
          </Link>
        </nav>

        {/* Статья — лист на кальке: заголовок, текст и CTA лежат на белой
            подложке, TOC — на полях листа, как заметки на распечатке. */}
        <div className="relative mx-auto max-w-[1200px] border border-[#15161a] bg-white px-12 pb-12 pt-14 max-md:px-5 max-md:pt-10">
          {/* Header — заголовок Geologica на белом листе, обложка под ним
              (обложки сохраняют свой кинематографичный стиль), моно-подпись/теги. */}
          {/* Header column matches the centered 68ch text column, so the cover
              image below the title is exactly text-width. */}
          <header className="mx-auto mb-12 max-w-[68ch]">
            <h1 className="font-heading text-balance text-[clamp(30px,4.4vw,52px)] font-extrabold leading-[1.05] tracking-[-0.03em] text-[#15161a]">
              {post.title}
            </h1>
            <div className="k-mono mt-6 flex flex-wrap items-center gap-x-3 gap-y-1 normal-case !tracking-normal">
              <Link
                href="/about"
                className="!text-[#15161a] transition-colors hover:!text-[#6b6e78]"
              >
                Влад Лямин
              </Link>
              <span aria-hidden>/</span>
              <time dateTime={post.published_at}>{date}</time>
              <span aria-hidden>/</span>
              <span>{minutes} мин чтения</span>
              {(post.tags ?? []).slice(0, 4).map((tag: string) => (
                <span key={tag} className="inline-flex items-center gap-1">
                  <span aria-hidden>/</span>
                  {tag}
                </span>
              ))}
            </div>
            {post.cover_image && (
              // Supabase public URLs — plain <img> avoids next/image remote config.
              // eslint-disable-next-line @next/next/no-img-element
              <img
                src={post.cover_image}
                alt={post.title}
                width={1200}
                height={630}
                // The cover is the LCP element: load it eagerly at high priority
                // while every in-body image below is deferred.
                loading="eager"
                fetchPriority="high"
                decoding="async"
                className="mt-8 aspect-[16/9] w-full border border-[#15161a] object-cover sm:aspect-[2/1]"
              />
            )}
          </header>

          {/* Centered text column with symmetric side rails: TOC lives in the
              left rail, the right rail stays empty — the 68ch content column
              sits exactly in the page center, aligned with the header above. */}
          <div className="flex flex-col gap-6 lg:grid lg:grid-cols-[13rem_minmax(0,68ch)_13rem] lg:justify-center lg:gap-10">
            {/* TOC (handles mobile/desktop internally) */}
            <TableOfContents html={contentHtml} />

            {/* Article content — col-start-2 keeps it centered even when the
                TOC renders nothing (fewer than 3 headings). */}
            <div className="min-w-0 lg:col-start-2">
              <CopyableCode html={contentHtml} />

              {/* Prev/Next */}
              {(prev || next) && (
                <nav className="mt-12 grid grid-cols-1 gap-3 text-sm sm:grid-cols-2">
                  {prev ? (
                    <a
                      href={`/blog/${prev.slug}`}
                      className="group relative overflow-hidden border border-[#15161a] bg-white p-4 transition-colors duration-200 hover:bg-[#f6f7f2]"
                    >
                      <span className="k-mono">&larr; Предыдущая</span>
                      <p className="mt-1 line-clamp-2 font-medium text-[#15161a] group-hover:underline">
                        {prev.title}
                      </p>
                    </a>
                  ) : (
                    <div className="max-sm:hidden" />
                  )}
                  {next ? (
                    <a
                      href={`/blog/${next.slug}`}
                      className="group relative overflow-hidden border border-[#15161a] bg-white p-4 text-right transition-colors duration-200 hover:bg-[#f6f7f2]"
                    >
                      <span className="k-mono">Следующая &rarr;</span>
                      <p className="mt-1 line-clamp-2 font-medium text-[#15161a] group-hover:underline">
                        {next.title}
                      </p>
                    </a>
                  ) : (
                    <div className="max-sm:hidden" />
                  )}
                </nav>
              )}

              {/* CTA. Copy follows the destination: posts that tease a product
                  point at it, everything else keeps the default audit offer. */}
              <div className="relative mt-10 overflow-hidden border border-[#15161a] bg-white p-6 text-center sm:p-8">
                <span aria-hidden className="absolute left-0 right-0 top-0 h-[3px] bg-[#c8f04c]" />
                <p className="k-mono mb-3">{cta.eyebrow}</p>
                <p className="font-heading mb-2 text-xl font-extrabold tracking-[-0.02em] text-[#15161a]">
                  {cta.title}
                </p>
                <p className="mx-auto mb-5 max-w-[48ch] text-sm text-[#6b6e78]">
                  {cta.text}
                </p>
                <a
                  href={cta.href}
                  {...(cta.external
                    ? { target: "_blank", rel: "noopener noreferrer" }
                    : {})}
                  className="k-btn k-btn--solid"
                >
                  {cta.label}
                </a>
              </div>
            </div>
          </div>
        </div>
      </article>

      {/* JSON-LD: BlogPosting */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: jsonLd({
            "@context": "https://schema.org",
            "@type": "BlogPosting",
            headline: post.title,
            description: post.meta_desc,
            datePublished: post.published_at,
            dateModified: post.published_at,
            wordCount: post.content_md?.trim().split(/\s+/).length ?? 0,
            inLanguage: "ru",
            articleSection: (post.tags ?? [])[0] ?? "AI-автоматизация",
            keywords: (post.tags ?? []).join(", "),
            ...(post.cover_image && { image: post.cover_image }),
            author: {
              "@type": "Person",
              "@id": `${blogUrl}/#person`,
              name: "Влад Лямин",
              url: `${blogUrl}/about`,
              sameAs: ["https://telegram.me/lyaminvl"],
            },
            publisher: {
              "@type": "Person",
              "@id": `${blogUrl}/#person`,
              name: "Влад Лямин",
              url: blogUrl,
            },
            mainEntityOfPage: {
              "@type": "WebPage",
              "@id": `${blogUrl}/blog/${post.slug}`,
            },
          }),
        }}
      />

      {/* JSON-LD: BreadcrumbList */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: jsonLd({
            "@context": "https://schema.org",
            "@type": "BreadcrumbList",
            itemListElement: [
              {
                "@type": "ListItem",
                position: 1,
                name: "Блог",
                item: `${blogUrl}/blog`,
              },
              {
                "@type": "ListItem",
                position: 2,
                name: post.title,
                item: `${blogUrl}/blog/${post.slug}`,
              },
            ],
          }),
        }}
      />

      {/* JSON-LD: FAQPage — only injected when FAQ section exists in content */}
      {faqItems.length > 0 && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: jsonLd({
              "@context": "https://schema.org",
              "@type": "FAQPage",
              mainEntity: faqItems.map(({ question, answer }) => ({
                "@type": "Question",
                name: question,
                acceptedAnswer: {
                  "@type": "Answer",
                  text: answer,
                },
              })),
            }),
          }}
        />
      )}

      {/* JSON-LD: HowTo — only for step-by-step articles with 3+ numbered steps */}
      {howToSteps && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: jsonLd({
              "@context": "https://schema.org",
              "@type": "HowTo",
              name: post.title,
              description: post.meta_desc,
              inLanguage: "ru",
              author: {
                "@type": "Person",
                "@id": `${blogUrl}/#person`,
                name: "Влад Лямин",
              },
              step: howToSteps.map((s, i) => ({
                "@type": "HowToStep",
                position: i + 1,
                name: s.name,
                text: s.text,
              })),
            }),
          }}
        />
      )}
    </div>
  );
}
