import { supabase } from "@/lib/supabase";
import Link from "next/link";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { TableOfContents } from "@/components/table-of-contents";
import { CopyableCode } from "@/components/copyable-code";
import SplitLines from "@/components/motion/SplitLines";

export const revalidate = 60;

interface Props {
  params: Promise<{ slug: string }>;
}

function readingTime(text: string): number {
  const words = text.trim().split(/\s+/).length;
  return Math.max(1, Math.round(words / 200));
}

// Safe JSON-LD serialization: prevents </script> injection by escaping < and >.
// JSON.stringify alone does not escape these, which could break the script block.
function jsonLd(obj: unknown): string {
  return JSON.stringify(obj)
    .replace(/</g, "\\u003c")
    .replace(/>/g, "\\u003e")
    .replace(/&/g, "\\u0026");
}

// Detect step-by-step articles and extract HowTo steps.
// Matches headings like "Шаг 1:", "Этап 2:", "Шаг первый" (3+ steps = HowTo).
function extractHowToSteps(html: string): { name: string; text: string }[] | null {
  const stepRe = /<h[23][^>]*>((?:Шаг|Этап|Пункт|Step)\s+[\dA-Za-zА-Яа-я]+[:.][^<]*)<\/h[23]>/gi;
  const steps: { name: string; text: string }[] = [];
  let m;
  while ((m = stepRe.exec(html)) !== null) {
    const raw = m[1].replace(/<[^>]+>/g, "").trim();
    // Extract description sentence after the colon, fall back to heading text
    const colonIdx = raw.indexOf(":");
    const name = colonIdx > -1 ? raw.slice(colonIdx + 1).trim() : raw;
    steps.push({ name, text: name });
  }
  return steps.length >= 3 ? steps : null;
}

// Extract FAQ Q&A pairs from HTML generated by the writer.
// Writer outputs: <strong>Question?</strong> followed by <p>Ответ: ...</p>
// Returns empty array if no FAQ section found.
function extractFaq(html: string): { question: string; answer: string }[] {
  const faqSection = html.match(
    /<h2[^>]*>Часто задаваемые вопросы<\/h2>([\s\S]*?)(?=<h2|$)/i
  );
  if (!faqSection) return [];

  const pairs: { question: string; answer: string }[] = [];
  // Match <p><strong>Question?</strong></p><p>Ответ: ...</p>
  const re = /<p>\s*<strong>([^<]+)<\/strong>\s*<\/p>\s*<p>([\s\S]*?)<\/p>/gi;
  let m;
  while ((m = re.exec(faqSection[1])) !== null) {
    const question = m[1].trim();
    // Strip "Ответ: " prefix and any inline HTML tags
    const answer = m[2].replace(/<[^>]+>/g, "").replace(/^Ответ:\s*/i, "").trim();
    if (question && answer) pairs.push({ question, answer });
  }
  return pairs;
}

// The cover image is also the first inline image in content_html. When we show
// the cover as a hero, strip that first occurrence so it isn't repeated.
function stripCoverImage(html: string, src: string | null): string {
  if (!src) return html;
  const esc = src.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const pWrapped = new RegExp(`<p>\\s*<img[^>]*src="${esc}"[^>]*>\\s*</p>`, "i");
  if (pWrapped.test(html)) return html.replace(pWrapped, "");
  return html.replace(new RegExp(`<img[^>]*src="${esc}"[^>]*>`, "i"), "");
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const { data: post } = await supabase
    .from("lvmn_blog_posts")
    .select("title, meta_desc, slug, tags, published_at, cover_image")
    .eq("slug", slug)
    .eq("status", "published")
    .single();

  if (!post) return {};

  const blogUrl = process.env.BLOG_URL ?? process.env.NEXT_PUBLIC_SITE_URL ?? "https://vladlyamin.ru";

  return {
    title: post.title,
    description: post.meta_desc ?? undefined,
    keywords: post.tags ?? undefined,
    openGraph: {
      title: post.title,
      description: post.meta_desc ?? undefined,
      type: "article",
      url: `${blogUrl}/blog/${post.slug}`,
      publishedTime: post.published_at,
      ...(post.cover_image && {
        images: [{ url: post.cover_image, width: 1200, height: 630 }],
      }),
    },
    twitter: {
      card: "summary_large_image",
      title: post.title,
      description: post.meta_desc ?? undefined,
      ...(post.cover_image && { images: [post.cover_image] }),
    },
    alternates: {
      canonical: `${blogUrl}/blog/${post.slug}`,
    },
  };
}

export default async function ArticlePage({ params }: Props) {
  const { slug } = await params;
  const { data: post } = await supabase
    .from("lvmn_blog_posts")
    .select("*")
    .eq("slug", slug)
    .eq("status", "published")
    .single();

  if (!post) notFound();

  const [{ data: prev }, { data: next }] = await Promise.all([
    supabase
      .from("lvmn_blog_posts")
      .select("slug, title")
      .eq("status", "published")
      .lt("published_at", post.published_at)
      .order("published_at", { ascending: false })
      .limit(1)
      .single(),
    supabase
      .from("lvmn_blog_posts")
      .select("slug, title")
      .eq("status", "published")
      .gt("published_at", post.published_at)
      .order("published_at", { ascending: true })
      .limit(1)
      .single(),
  ]);

  const date = new Date(post.published_at).toLocaleDateString("ru-RU", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const minutes = readingTime(post.content_md);
  const blogUrl = process.env.BLOG_URL ?? process.env.NEXT_PUBLIC_SITE_URL ?? "https://vladlyamin.ru";
  const rawHtml = post.content_html ?? "";
  // With a cover hero, drop the duplicate first inline image from the body.
  const contentHtml = post.cover_image ? stripCoverImage(rawHtml, post.cover_image) : rawHtml;
  const faqItems = extractFaq(rawHtml);
  const howToSteps = extractHowToSteps(rawHtml);

  return (
    <>
      <article className="px-[6vw] pb-24">
        {/* Breadcrumbs */}
        {/* mt clears the fixed HUD label ("≡ Блог") pinned to the same top-left corner */}
        <nav className="mono-label mx-auto mt-10 mb-8 max-w-[68ch] text-ink-muted">
          <Link
            href="/blog"
            className="transition-colors hover:text-ink"
          >
            &larr; Блог
          </Link>
        </nav>

        {/* Header — poster H1 (Literata, line-reveal), plain cover image
            below the title, mono byline/tags. */}
        {/* Header column matches the centered 68ch text column, so the cover
            image below the title is exactly text-width. */}
        <header className="mx-auto mb-12 max-w-[68ch]">
          <SplitLines
            as="h1"
            className="font-display text-[clamp(32px,6vw,72px)] leading-[1.02] text-ink"
          >
            {post.title}
          </SplitLines>
          <div className="mono-label mt-6 flex flex-wrap items-center gap-x-3 gap-y-1 text-ink-muted">
            <Link
              href="/about"
              className="text-ink transition-colors hover:text-lime-dark"
            >
              Влад Лямин
            </Link>
            <span aria-hidden>/</span>
            <time dateTime={post.published_at}>{date}</time>
            <span aria-hidden>/</span>
            <span>{minutes} мин чтения</span>
            {(post.tags ?? []).slice(0, 4).map((tag: string) => (
              <span key={tag} className="inline-flex items-center gap-1">
                <span aria-hidden>/</span>
                {tag}
              </span>
            ))}
          </div>
          {post.cover_image && (
            // Supabase public URLs — plain <img> avoids next/image remote config.
            // eslint-disable-next-line @next/next/no-img-element
            <img
              src={post.cover_image}
              alt=""
              aria-hidden
              className="mt-8 aspect-[16/9] w-full border border-line object-cover sm:aspect-[2/1]"
            />
          )}
        </header>

        {/* Centered text column with symmetric side rails: TOC lives in the
            left rail, the right rail stays empty — the 68ch content column
            sits exactly in the page center, aligned with the header above. */}
        <div className="flex flex-col gap-6 lg:grid lg:grid-cols-[13rem_minmax(0,68ch)_13rem] lg:justify-center lg:gap-10">
          {/* TOC (handles mobile/desktop internally) */}
          <TableOfContents html={contentHtml} />

          {/* Article content — col-start-2 keeps it centered even when the
              TOC renders nothing (fewer than 3 headings). */}
          <div className="min-w-0 lg:col-start-2">
            <CopyableCode html={contentHtml} />

            {/* Prev/Next */}
            {(prev || next) && (
              <nav className="mt-12 grid grid-cols-1 sm:grid-cols-2 gap-3 text-sm">
                {prev ? (
                  <a
                    href={`/blog/${prev.slug}`}
                    className="group relative p-4 border border-line bg-white overflow-hidden transition-colors duration-200 hover:border-ink"
                  >
                    <span className="font-mono text-[11px] uppercase tracking-wider text-ink-muted">
                      ← Предыдущая
                    </span>
                    <p className="text-ink font-medium mt-1 line-clamp-2 group-hover:underline decoration-ink underline-offset-4">
                      {prev.title}
                    </p>
                  </a>
                ) : (
                  <div />
                )}
                {next ? (
                  <a
                    href={`/blog/${next.slug}`}
                    className="group relative p-4 border border-line bg-white overflow-hidden text-right transition-colors duration-200 hover:border-ink"
                  >
                    <span className="font-mono text-[11px] uppercase tracking-wider text-ink-muted">
                      Следующая →
                    </span>
                    <p className="text-ink font-medium mt-1 line-clamp-2 group-hover:underline decoration-ink underline-offset-4">
                      {next.title}
                    </p>
                  </a>
                ) : (
                  <div />
                )}
              </nav>
            )}

            {/* CTA */}
            <div className="relative mt-10 p-6 sm:p-8 bg-white border border-line text-center overflow-hidden">
              <span aria-hidden className="absolute top-0 left-0 right-0 h-[3px] bg-lime" />
              <p className="font-mono text-[11px] uppercase tracking-[0.15em] text-ink-muted mb-3">
                AI-аудит
              </p>
              <p className="font-heading text-xl font-extrabold tracking-[-0.02em] text-ink mb-2">
                Автоматизируйте свой бизнес с AI
              </p>
              <p className="text-sm text-ink-muted mb-5 max-w-[48ch] mx-auto">
                Напишите «Аудит» в Telegram — разберу ваши процессы и предложу конкретное решение
              </p>
              <a
                href={post.cta_url ?? "https://t.me/lyaminvl?text=Аудит"}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-block px-6 py-3 bg-ink text-paper text-sm font-medium hover:bg-black transition-colors"
              >
                Написать в Telegram →
              </a>
            </div>
          </div>
        </div>
      </article>

      {/* JSON-LD: BlogPosting */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: jsonLd({
            "@context": "https://schema.org",
            "@type": "BlogPosting",
            headline: post.title,
            description: post.meta_desc,
            datePublished: post.published_at,
            dateModified: post.published_at,
            wordCount: post.content_md?.trim().split(/\s+/).length ?? 0,
            inLanguage: "ru",
            articleSection: (post.tags ?? [])[0] ?? "AI-автоматизация",
            keywords: (post.tags ?? []).join(", "),
            ...(post.cover_image && { image: post.cover_image }),
            author: {
              "@type": "Person",
              "@id": `${blogUrl}/#person`,
              name: "Влад Лямин",
              url: `${blogUrl}/about`,
              sameAs: ["https://t.me/lyaminvl"],
            },
            publisher: {
              "@type": "Person",
              "@id": `${blogUrl}/#person`,
              name: "Влад Лямин",
              url: blogUrl,
            },
            mainEntityOfPage: {
              "@type": "WebPage",
              "@id": `${blogUrl}/blog/${post.slug}`,
            },
          }),
        }}
      />

      {/* JSON-LD: BreadcrumbList */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: jsonLd({
            "@context": "https://schema.org",
            "@type": "BreadcrumbList",
            itemListElement: [
              {
                "@type": "ListItem",
                position: 1,
                name: "Блог",
                item: `${blogUrl}/blog`,
              },
              {
                "@type": "ListItem",
                position: 2,
                name: post.title,
                item: `${blogUrl}/blog/${post.slug}`,
              },
            ],
          }),
        }}
      />

      {/* JSON-LD: FAQPage — only injected when FAQ section exists in content */}
      {faqItems.length > 0 && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: jsonLd({
              "@context": "https://schema.org",
              "@type": "FAQPage",
              mainEntity: faqItems.map(({ question, answer }) => ({
                "@type": "Question",
                name: question,
                acceptedAnswer: {
                  "@type": "Answer",
                  text: answer,
                },
              })),
            }),
          }}
        />
      )}

      {/* JSON-LD: HowTo — only for step-by-step articles with 3+ numbered steps */}
      {howToSteps && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: jsonLd({
              "@context": "https://schema.org",
              "@type": "HowTo",
              name: post.title,
              description: post.meta_desc,
              inLanguage: "ru",
              author: {
                "@type": "Person",
                "@id": `${blogUrl}/#person`,
                name: "Влад Лямин",
              },
              step: howToSteps.map((s, i) => ({
                "@type": "HowToStep",
                position: i + 1,
                name: s.name,
                text: s.text,
              })),
            }),
          }}
        />
      )}
    </>
  );
}
